name: curriculum-tool

services:
  laravel:
    build:
      context: laravel/
    env_file: laravel/.env.docker
    ports:
      - 9000:80
    volumes:
      - sessions:/var/www/html/storage/framework/sessions
      - uploads:/var/www/html/storage/app
    depends_on:
      db:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  db:
    image: postgres:17.10-trixie
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: laravel/.env.postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      timeout: 10s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
    
  syllabus-parser:
    build:
      context: python/services/syllabi_service/
    volumes:
      - syllabus-parser-logs:/usr/src/logs
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 256M
  
  lo-mapper:
    build:
      context: python/services/lo_mapping_service/
    volumes:
      - lo-mapper-logs:/usr/src/logs
    env_file: python/services/lo_mapping_service/.env.docker
    environment:
      LARAVEL_API_URL: http://laravel/api/microservices/lo-mapping/ai-suggestions/store
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 256M
    
volumes:
  pgdata:
  sessions:
  uploads:
  syllabus-parser-logs:
  lo-mapper-logs:

# TODO: Set up Python services!